apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cenza-website
  annotations:
    kubernetes.io/ingress.global-static-ip-name: cenza
    networking.gke.io/managed-certificates: cenza
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: cenza-website
      port:
        number: 80